### ISSUE TITLE
It is possible to have old settings file and new config resulting in odd status info.

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/device-agent#102]
### Current Behavior

When a new device config is applied via Web UI, the status info refreshes but the older Device Name is still shown.

![image](https://github.com/flowforge/flowforge-device-agent/assets/44235289/bb51fb2d-2c20-483c-ab82-e6d8cd8a0e5b)

![image](https://github.com/flowforge/flowforge-device-agent/assets/44235289/30d2d573-1925-412f-8e85-767d00b2abbd)

This suggests that `agent.currentSettings.env.FF_DEVICE_NAME` was not updated (sinces that is where the value comes from.

Confusingly, the device Id appears to be correct and that comes from  `agent.currentSettings.env.FF_DEVICE_ID`

### Expected Behavior

correct values to be displayed on status page.
correct values in env var

### Steps To Reproduce

with a running device agent (with an instance & snapshot assigned):

1. create a new device & copy its config
2. apply the config to the running device via the devices Web UI

#### NOTES:
* Restarting the device agent does not fix this.

### Environment

- FlowForge version: 1.8-git
- Agent Version - 0.9-git

**Comment by Steve-Mcl** [comment]
Further findings:

1. `/project/settings.json` holds old values


`/opt/flowforge-device/project$ cat settings.json | jq .`
```json

{
  "credentialSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "port": 5001,
  "codeEditor": "monaco",
  "forge-light": {
    "launcherVersion": "0.9.0",
    "forgeURL": "https://forge.xxxxxxxxxx.xxx",
    "projectURL": "https://forge.xxxxxxxxxxxxxxx/device/EpkyL0OyqX/overview"  // << OLD Device ID
  },
  "editorTheme": {
    "theme": "forge-light",
    "codeEditor": {
      "lib": "monaco"
    },
    "tours": false
  },
  "flowforge": {
    "forgeURL": "https://forge.xxxxxxxxxxx.xxx",
    "teamID": "WO2NoXgaex",
    "projectLink": {
      "token": "ffd_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "broker": {
        "url": "wss://mqtt.xxxxxxxxxxxxxxx.xxx",
        "username": "device:WO2NoXgaex:EpkyL0OyqX",    // << OLD Device ID
        "password": "ffbd_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      }
    }
  }
}
```

For reference, this is the device yml

```yaml
deviceId: nqJykYLb98  // << Correct
token: ffd__xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
credentialSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
forgeURL: https://forge.xxxxxxxxxx.xxx
brokerURL: wss://mqtt.xxxxxxxxxx.xxx
brokerUsername: device:WO2NoXgaex:nqJykYLb98 // << Correct
brokerPassword: ffbd_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
